### ISSUE TITLE
JupyterHub logs

### ISSUE THREAD

**Issue by alexraju91** [harvard/cloudJHub#10]
where can I see the jupyterhub logs?

`journalctl -u jupyterhub.service` gives only minimal information.

**Comment by alexraju91** [comment]
Found logs in `/var/log/jupyterhub`

**Comment by farassadek** [comment]
The logs path is a parameter in /etc/jupyterhub/jupyterhub_config.py
By default it is /var/log/jupyterhub

**Comment by alexraju91** [comment]
I thought there is some easy way to forward logs from sysvinit to journald. Closing it.
