### ISSUE TITLE
Spawner: Unable to locate credentials

### ISSUE THREAD

**Issue by h4gen** [harvard/cloudJHub#11]
Hey!

First, thank you for your amazing work! What you did here is what i was looking for and dreaming of for a long time :) Really great!

So far I was able to run the launch script and connect to the hub. However, when I log in the message 'Unable to locate credentials' is showed.

![image](https://user-images.githubusercontent.com/12556763/44591296-9ed1b080-a7bd-11e8-8a1b-e168955796ab.png)

What is a possible solution or where can I start looking for the bug?

Thanks alot!

**Comment by farassadek** [comment]
Hi, 
Thanks for the complement. 

Can you please check if the manager have the required role to create EC2 instances?

Faras

**Comment by h4gen** [comment]
Indeed he does not! How can this happen? What did I do wrong?

**Comment by farassadek** [comment]
Did you follow instruction on the below installation page ? https://github.com/harvard/cloudJHub/blob/master/Documentation/installation.md
There is a part about creating a role, then use the role ARN in the secure.py file.
Check it out and let me know

**Comment by h4gen** [comment]
Alright, own stupidity. Needed some tries until everything was running and in the last run I really forgot the ARN.
