### ISSUE TITLE
Key Path error

### ISSUE THREAD

**Issue by alexraju91** [harvard/cloudJHub#8]
`launch_cluster/secure.py.example`

```
KEY_NAME = "aws.pem changeme"
KEY_PATH = "~/.ssh/%s" % KEY_NAME
```

So, if I give as below, it's obviously wrong. THE KEY_NAME shouldn't have the `.pem` extension, whereas the KEY_PATH needs to have. 

```
KEY_NAME = "something.pem"
KEY_PATH = "~/.ssh/%s" % KEY_NAME
```

**Comment by farassadek** [comment]
Alex
The doc in  https://github.com/harvard/cloudJHub/blob/master/Documentation/installation.md 
if you copy a key "jupyter_key.pem" to for example /home/ec2-user/.ssh then the secure.py should be 

 AWS_ACCESS_KEY_ID = ""
 AWS_SECRET_KEY = ""
 KEY_NAME = "jupyter_key"
 KEY_PATH = "/home/ec2-user/.ssh/%s.pem" % KEY_NAME
.
.

**Comment by alexraju91** [comment]
Thank you @farassadek . 
I think you need to make the necessary changes in `secure.py.example` file also as people would be making their `secure.py` file from this.

**Comment by farassadek** [comment]
I believe you are right, actually you can update and merge to the repo

**Comment by farassadek** [comment]
The key might not not be .pem.
